//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessForWomen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public int Id { get; set; }
        public string Baslık { get; set; }
        public string İcerik { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<int> EgitmenId { get; set; }
    
        public virtual Egitmenler Egitmenler { get; set; }
    }
}
