//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessForWomen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egitmenler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Egitmenler()
        {
            this.Kullanıcı = new HashSet<Kullanıcı>();
        }
    
        public int Id { get; set; }
        public string AdiSoyadi { get; set; }
        public string Brans { get; set; }
        public string İcerik { get; set; }
        public Nullable<int> SosyalMedyaHesaplarıID { get; set; }
        public string Resim { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<int> BlogId { get; set; }
    
        public virtual Blog Blog { get; set; }
        public virtual SosyalMedyaHesapları SosyalMedyaHesapları { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanıcı> Kullanıcı { get; set; }
    }
}
