//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessForWomen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SosyalMedyaHesapları
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SosyalMedyaHesapları()
        {
            this.Egitmenler = new HashSet<Egitmenler>();
        }
    
        public int Id { get; set; }
        public string Facebook { get; set; }
        public string Twiter { get; set; }
        public string İnstagram { get; set; }
        public string G_Plus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Egitmenler> Egitmenler { get; set; }
    }
}
